# Generated by Django 5.0.7 on 2024-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clint_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('companyname', models.CharField(max_length=200, null=True)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('pan', models.IntegerField(max_length=100, null=True)),
                ('company_id', models.CharField(max_length=200)),
            ],
        ),
    ]
